project/course_search_judgement/urls.py
from django.urls import path
from . import views
app_name = 'course_search_judgement'

urlpatterns = [
    path('search_from/', views.search_from, name='search_from'),
    path('search_result/', views.search_result, name='search_result'),  #结果查询显示页面
    path('add_judgement/submit', views.add_judgement),  # 提交课程的评价结果
    path('search_result/thumb', views.thumb, name='thumb'),# 提交课程的评价结果
]

project/log_sign/urls.py
from django.urls import path
from . import views
app_name = 'log_sign'
urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('register/', views.register, name='register'),
]

project/my_account/urls.py
from django.urls import path
from . import views
app_name = 'my_account'
urlpatterns = [
    path('', views.my_account, name='my_account'),
    path('modify_judgement/', views.modify_judgement),
    path('delete_judgement/', views.delete),
    path('thumb/<p2>', views.thumb, name='thumb')

]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('log_sign.urls')),
    path('', include('course_search_judgement.urls')),
    path('my_account/', include('my_account.urls'))
]

project/my_account/models.py
from django.db import models

# Create your models here.

project/log_sign/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class normal_user_form(UserCreationForm):
    student_number = forms.CharField(required=False)
    phone = forms.CharField(required=False)

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'email', 'student_number', 'phone']

project/my_account/views.py
from datetime import datetime
from django.shortcuts import render, redirect
from course_search_judgement.models import course, judgement_system, thumb_up
from log_sign.models import normal_user
from django.contrib.auth.models import User


def my_account(request):
    # 我的账号页面
    user = request.user
    user_ = normal_user.objects.filter(user=user)
    user_id = user_[0].id
    judges = judgement_system.objects.filter(name_id=user_id)
    normal_user_ = normal_user.objects.filter(id=user_id)
    judges.student_number = normal_user_[0].student_number
    judges.phone = normal_user_[0].phone
    auth_ = User.objects.filter(id=normal_user_[0].user_id)
    judges.email = auth_[0].email
    judges.username = auth_[0].username
    for judge in judges:
        my_course = course.objects.filter(id=judge.course_id)
        judge.course_name = my_course[0].name
        judge.course_teacher = my_course[0].teacher
        judge.course_type = my_course[0].type
        judge.course_credit = my_course[0].credit
        thumb_ = thumb_up.objects.filter(user_id_id=user_id, judgement_id_id=judge.id)
        if thumb_:
            judge.tb = 1
        else:
            judge.tb = 0
    return render(request, 'my_account.html', {'my_account': judges})


def thumb(request, p2):
    # 点赞功能函数
    user = request.user
    user_ = normal_user.objects.filter(user=user)
    user_id = user_[0].id
    thumb_ = thumb_up.objects.filter(user_id_id=user_id, judgement_id_id=p2)
    if thumb_:
        judge = judgement_system.objects.get(id=p2)
        judge.number_of_thumb_up = judge.number_of_thumb_up - 1
        judge.save()
        thumb_ = thumb_up.objects.filter(judgement_id_id=p2, user_id_id=user_id)
        thumb_.delete()
    else:
        judge = judgement_system.objects.get(id=p2)
        judge.number_of_thumb_up = judge.number_of_thumb_up + 1
        judge.save()
        thumb_up(judgement_id_id=p2,
                 user_id_id=user_id).save()
    return redirect("/my_account/")


def modify_judgement(request):
    # 修改评论功能函数
    if request.method == "POST":
        comment_of_the_course = request.POST.get("comment_of_the_course")
        comment_of_the_teacher = request.POST.get("comment_of_the_teacher")
        the_constitution_of_grade = request.POST.get("the_constitution_of_grade ")
        time_for_homework = request.POST.get("time_for_homework")
        hard_core_mark = request.POST.get("hard_core_mark")
        recommend_mark = request.POST.get("recommend_mark")
        mark_of_interest = request.POST.get("mark_of_interest")
        judge = request.POST.get("id")
        modify_judge = judgement_system.objects.filter(id=judge)
        course_id = modify_judge[0].course_id
        modify_judge.delete()
        user = request.user
        user_ = normal_user.objects.filter(user=user)
        user_id = user_[0].id
        judgement_system(create_date=datetime.now(),
                         comment_of_the_course=comment_of_the_course,
                         comment_of_the_teacher=comment_of_the_teacher,
                         the_constitution_of_grade=the_constitution_of_grade,
                         time_for_homework=time_for_homework,
                         course_id=course_id,
                         hard_core_mark=hard_core_mark,
                         recommend_mark=recommend_mark,
                         mark_of_interest=mark_of_interest,
                         name_id=user_id).save()
    return redirect("/my_account/")


def delete(request):
    # 删除评论功能函数
    if request.method == "POST":
        judge = request.POST.get("id")
        delete_judge = judgement_system.objects.filter(id=judge)
        delete_judge.delete()
    return redirect("/my_account/")

project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-Hans">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}base{% endblock %}</title>
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet"/>
    <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    {% block css %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my-nav" aria-expanded="false">
                <span class="sr-only">切换导航条</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'log_sign:home' %}" style="color: white">课程网站</a>
        </div>

        <div class="collapse navbar-collapse" id="my-nav">
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'course_search_judgement:search_from' %}" style="color: white">搜索</a></li>
                    <li><a href="{% url 'my_account:my_account' %}" style="color: white">个人中心</a></li>
                    <li><a href="{% url 'log_sign:logout' %}" style="color: white">退出</a></li>
                {% else %}
                    <li><a href="{% url 'log_sign:login' %}" style="color: white">登录</a></li>
                    <li><a href="{% url 'log_sign:register' %}" style="color: white">注册</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %}{% endblock %}

<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

</body>
</html>

project/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}主页{% endblock %}
{% block css %}<link href="{% static 'css/home.css' %}" rel="stylesheet"/>{% endblock %}

{% block content %}
    <div class="home-bg">

    </div>
{% endblock %}

project/templates/log_in.html
{% extends 'base.html' %}
{% load static %}

{% block title %}登录{% endblock %}
{% block css %}<link href="{% static 'css/register.css' %}" rel="stylesheet"/>{% endblock %}

{% block content %}
    {% csrf_token %}
    <div class="container">
        <div class="col-md-4 col-md-offset-7" id="login-box">
            <form class='form-login' action="" method="post">
                {% csrf_token %}
                <h4 class="text-center">登录</h4>
                <div class="form-group">
                    <label for="username" class="col-sm-3 control-label">用户名:</label>
                    <div class="col-sm-9">
                        <input type="text" name='username' class="form-control" id="id_username" placeholder="Username" autofocus required>
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password1" class="col-sm-3 control-label">密码:</label>
                    <div class="col-sm-9">
                        <input type="password" name='password' class="form-control" id="id_password" placeholder="Password" required>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary" style="outline: none">登录</button>
            </form>
        </div>
    </div>
{% endblock %}

project/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}注册{% endblock %}
{% block css %}<link href="{% static 'css/register.css' %}" rel="stylesheet"/>{% endblock %}

{% block content %}
    <div class="container">
        <div class="col-md-4 col-md-offset-7" id="register-box">
            <form class='form-login' action="" method="post">
                <h4 class="text-center">注册</h4>
                {% csrf_token %}
                <div class="form-group">
                    <label for="username" class="col-sm-3 control-label">用户名:</label>
                    <div class="col-sm-9">
                        <input type="text" name='username' class="form-control" id="id_username" placeholder="Username" autofocus required>
                    </div>
                </div>
                {% for error in register_forms.errors.username %}
                    <p class="tip"><span class="star">*</span>{{ error }}</p>
                {% endfor %}

                <div class="form-group">
                    <label for="id_password1" class="col-sm-3 control-label">密码:</label>
                    <div class="col-sm-9">
                        <input type="password" name='password1' class="form-control" id="id_password1" placeholder="Password1" required>
                    </div>
                </div>
                {% for error in register_forms.errors.password1 %}
                    <p class="tip"><span class="star">*</span>{{ error }}</p>
                {% endfor %}

                <div class="form-group">
                    <label for="id_password2" class="col-sm-3 control-label">确认密码:</label>
                    <div class="col-sm-9">
                        <input type="password" name='password2' class="form-control" id="id_password2" placeholder="Password2" required>
                    </div>
                </div>
                {% for error in register_forms.errors.password2 %}
                    <p class="tip"><span class="star">*</span>{{ error }}</p>
                {% endfor %}

                <div class="form-group">
                    <label for="id_email" class="col-sm-3 control-label">邮箱:</label>
                    <div class="col-sm-9">
                        <input type="text" name='email' class="form-control" id="id_email" placeholder="Email" required>
                    </div>
                </div>
                {% for error in register_forms.errors.email %}
                    <p class="tip"><span class="star">*</span>{{ error }}</p>
                {% endfor %}

                <div class="form-group">
                    <label for="id_student_number" class="col-sm-3 control-label">学号:</label>
                    <div class="col-sm-9">
                        <input type="text" name='student_number' class="form-control" id="id_student_number" placeholder="Student Number" required>
                    </div>
                </div>
                {% for error in register_forms.errors.student_number %}
                    <p class="tip"><span class="star">*</span>{{ error }}</p>
                {% endfor %}

                <div class="form-group">
                    <label for="id_phone" class="col-sm-3 control-label">联系方式:</label>
                    <div class="col-sm-9">
                        <input type="text" name='phone' class="form-control" id="id_phone" placeholder="Phone" required>
                    </div>
                </div>
                {% for error in register_forms.errors.phone %}
                    <p class="tip"><span class="star">*</span>{{ error }}</p>
                {% endfor %}

                <button type="submit" class="btn btn-primary pull-right" style="outline: none">提交</button>
            </form>
        </div>
    </div>
{% endblock %}

project/templates/search_from.html
{% extends 'base.html' %}
{% load static %}

{% block title %}搜索{% endblock %}
{% block css %}<link href="{% static 'css/search_from.css' %}" rel="stylesheet"/>{% endblock %}

{% block content %}
<div class="container">
    <div class="img">
    </div>
    <div class="search">
        {% csrf_token %}
        <form action="/search_result/" method="post">
            <img src={% static "/img/xiaohui.png" %} alt="校徽">
            <input type="text" name="q" placeholder="请输入搜索条件" onFocus="if(value==defaultValue){value='';this.style.color='#000'}"
                   onBlur="if(!value){value=defaultValue;this.style.color='#999'}" style="color:#999999;outline: none">
            <button type="submit" value="搜索" style="outline: none">搜索</button>
            <button type="submit" name="p" class="category" value ="人文学科" style="outline: none">人文学科</button>&nbsp&nbsp
            <button type="submit" name="p" class="category" value ="社会科学" style="outline: none">社会科学</button>&nbsp&nbsp
            <button type="submit" name="p" class="category" value ="自然科学" style="outline: none">自然科学</button>&nbsp&nbsp
            <button type="submit" name="p" class="category" value ="工程科学与技术" style="outline: none">工程科学与技术</button>&nbsp&nbsp
            <button type="submit" name="r" class="category" value ="热门课程" style="outline: none">热门课程</button>
        </form>
    </div>
</div>
{% endblock %}